import type { Metadata } from "next";
import { ReactNode } from 'react';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '../theme';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body>
        {/* Wrap the app with the MUI ThemeProvider */}
        <ThemeProvider theme={theme}>
          <CssBaseline />  {/* Apply a consistent baseline for all components */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
