// Mock data for meetings
export const allMeetings = [
  {
    id: 1,
    name: "Project Kickoff",
    client: "Sarah Johnson",
    date: "2024-03-15",
    time: "10:00 AM",
    duration: "60 min",
    status: "upcoming",
  },
  {
    id: 2,
    name: "Design Review",
    client: "Alex Chen",
    date: "2024-03-17",
    time: "2:00 PM",
    duration: "45 min",
    status: "upcoming",
  },
  {
    id: 3,
    name: "Client Consultation",
    client: "Emily Brown",
    date: "2024-03-10",
    time: "11:30 AM",
    duration: "30 min",
    status: "past",
  },
  {
    id: 4,
    name: "Team Sync",
    client: "Internal Team",
    date: "2024-03-12",
    time: "3:00 PM",
    duration: "60 min",
    status: "canceled",
  },
  {
    id: 5,
    name: "Product Demo",
    client: "Michael Lee",
    date: "2024-03-20",
    time: "1:00 PM",
    duration: "45 min",
    status: "upcoming",
  },
];
